version: '3.8'

services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile
    image: strapi-app
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
      APP_KEYS: ll9Ajd4WE3ah1ige+ZfEmA==,g6ZzGRQWAz4mjoyao1Hqow==,KQDMVYWriwv+ZmXCsPcA+g==,jdxmv4WztutzVA/imBpzHw==
      API_TOKEN_SALT: 5GF0YnNCSwHe53IkVfEyLg==
      ADMIN_JWT_SECRET: gbIYOiXGivj78jLK4r7UlA==
      TRANSFER_TOKEN_SALT: XBDYtuJtUbNBZCwBALziug==
      ENCRYPTION_KEY: OsT2GaiohL65qg1pg4PHdA==
      FLAG_NPS: true
      FLAG_PROMOTE_EE: true
    volumes:
      - ./strapi:/opt/app
      - ./strapi/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi_network
    depends_on:
      - db

  db:
    container_name: strapi_db
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - strapi_network

volumes:
  strapi-data:

networks:
  strapi_network:
    driver: bridge 