/**
 * Open Graph image paths for each minisite page.
 *
 * SSOT for the per-page social-share preview. Each minisite page's
 * generateMetadata() reads the matching path and emits a 1200×630 og:image
 * tag. Images are generated by scripts/generate-og-images.mjs from the
 * existing minisite photography — never inline tooling, always real
 * source material so previews stay honest.
 */

import { UPCYCLING_BASE } from '@/config/upcycling-routes'

const OG_BASE = `${UPCYCLING_BASE}/og` as const

export const OG_IMAGES = {
  landing:        `${OG_BASE}/landing.jpg`,
  wirkung:        `${OG_BASE}/wirkung.jpg`,
  applications:   `${OG_BASE}/applications.jpg`,
  gallery:        `${OG_BASE}/gallery.jpg`,
  businessplan:   `${OG_BASE}/businessplan.jpg`,
  buildYourOwn:   `${OG_BASE}/build-your-own.jpg`,
  status:         `${OG_BASE}/status.jpg`,
  lenovoL2251pwd: `${OG_BASE}/lenovo-l2251pwd.jpg`,
} as const

/** Shape a Metadata.openGraph + twitter block for a minisite page. */
export function ogFor(
  key: keyof typeof OG_IMAGES,
  meta: { title: string; description: string },
  options: { type?: 'website' | 'article' } = {},
) {
  const image = OG_IMAGES[key]
  return {
    openGraph: {
      title: meta.title,
      description: meta.description,
      type: options.type ?? 'website',
      images: [{ url: image, width: 1200, height: 630, alt: meta.title }],
    },
    twitter: {
      card: 'summary_large_image' as const,
      title: meta.title,
      description: meta.description,
      images: [image],
    },
  }
}
