/**
 * Open Graph image paths for each minisite page.
 *
 * SSOT for the per-page social-share preview. Each minisite page's
 * generateMetadata() reads the matching path and emits a 1200×630 og:image
 * tag. Images are generated by scripts/generate-og-images.mjs from the
 * existing minisite photography — never inline tooling, always real
 * source material so previews stay honest.
 *
 * The 1200×630 spec matches what Facebook, LinkedIn, Slack, X, iMessage,
 * WhatsApp and Discord all converge on. The shared structured payload
 * below is consumed by Next.js `Metadata.openGraph` and produces both
 * og:image and twitter:image tags from one source.
 */

export const OG_IMAGES = {
  landing:        '/projects/upcycling/og/landing.jpg',
  wirkung:        '/projects/upcycling/og/wirkung.jpg',
  applications:   '/projects/upcycling/og/applications.jpg',
  gallery:        '/projects/upcycling/og/gallery.jpg',
  businessplan:   '/projects/upcycling/og/businessplan.jpg',
  buildYourOwn:   '/projects/upcycling/og/build-your-own.jpg',
  status:         '/projects/upcycling/og/status.jpg',
  lenovoL2251pwd: '/projects/upcycling/og/lenovo-l2251pwd.jpg',
} as const

/** Shape a Metadata.openGraph + twitter block for a minisite page.
 *  Saves having to repeat dimensions/alt/twitter-card across every page. */
export function ogFor(
  key: keyof typeof OG_IMAGES,
  meta: { title: string; description: string },
  options: { type?: 'website' | 'article' } = {},
) {
  const image = OG_IMAGES[key]
  return {
    openGraph: {
      title: meta.title,
      description: meta.description,
      type: options.type ?? 'website',
      images: [{ url: image, width: 1200, height: 630, alt: meta.title }],
    },
    twitter: {
      card: 'summary_large_image' as const,
      title: meta.title,
      description: meta.description,
      images: [image],
    },
  }
}
