/**
 * ROUTES — SSOT for all application paths.
 *
 * Static routes are plain strings. Dynamic routes are functions.
 * Never hardcode paths in components — import from here.
 */
export const ROUTES = {
  admin: {
    dashboard:          '/admin',
    erfassung:          '/admin/erfassung',
    erfassungNew:       '/admin/erfassung/new',
    products:           '/admin/products',
    product:            (id: string) => `/admin/products/${id}`,
    productFactsheet:   (id: string) => `/admin/products/${id}/factsheet`,
    decisions:          '/admin/decisions',
    decisionNew:        '/admin/decisions/new',
    decision:           (id: string) => `/admin/decisions/${id}`,
    protocols:          '/admin/protocols',
    protocolNew:        '/admin/protocols/new',
    protocol:           (id: string) => `/admin/protocols/${id}`,
    approvals:          '/admin/approvals',
    users:              '/admin/users',
    user:               (id: string) => `/admin/users/${id}`,
    tasks:              '/admin/tasks',
    taskNew:            '/admin/tasks/new',
    task:               (id: string) => `/admin/tasks/${id}`,
    tasksAnalytics:     '/admin/tasks/analytics',
    taskProjects:       '/admin/tasks/projects',
    taskProjectNew:     '/admin/tasks/projects/new',
    taskProject:        (id: string) => `/admin/tasks/projects/${id}`,
    projects:           '/admin/projects',
    project:            (slug: string) => `/admin/projects/${slug}`,
    team:               '/admin/team',
    teamActivity:       '/admin/team/activity',
    workshops:          '/admin/workshops',
    workshopsNew:       '/admin/workshops/new',
    workshopsInstances: '/admin/workshops/instances',
    workshopInstance:   (id: string) => `/admin/workshops/instances/${id}`,
    workshopProposal:   (id: string) => `/admin/workshops/proposals/${id}`,
    services:           '/admin/services',
    serviceNew:         '/admin/services/new',
    itHilfe:            '/admin/it-hilfe',
    marketplace:        '/admin/marketplace',
    listing:            (id: string) => `/admin/marketplace/${id}`,
    hirn:               '/admin/hirn',
    content:            '/admin/content',
    contentSubmissions: '/admin/content/submissions',
    contentBlog:        '/admin/content/blog',
    contentBlogNew:     '/admin/content/blog/new',
    categories:         '/admin/content/categories',
    categoryNew:        '/admin/content/categories/new',
    contentPages:       '/admin/content/pages',
    contentPageNew:     '/admin/content/pages/new',
    contentPage:        (id: string) => `/admin/content/pages/${id}`,
    contentMedia:       '/admin/content/media',
    locations:          '/admin/locations',
    locationNew:        '/admin/locations/new',
    location:           (id: string) => `/admin/locations/${id}`,
    analyse:            '/admin/analyse',
    analyseFinanzen:    '/admin/analyse/finanzen',
    analyseKennzahlen:  '/admin/analyse/kennzahlen',
    analyseWirkung:     '/admin/analyse/wirkung',
    analyseTransparenz: '/admin/analyse/transparenz',
    settings:           '/admin/settings',
  },
  public: {
    home:                     '/',
    shop:                     '/shop',
    shopSearch:               '/shop/search',
    marketplace:              '/marketplace',
    marketplaceSell:          '/marketplace/sell',
    marketplaceListing:       (id: string) => `/marketplace/${id}`,
    marketplaceCheckout:      (id: string) => `/marketplace/checkout/${id}`,
    seller:                   (id: string) => `/sellers/${id}`,
    itHilfe:                  '/it-hilfe',
    itHilfeCreate:            '/it-hilfe/create',
    itHilfeMy:                '/it-hilfe/my',
    itHilfeMyOffers:          '/it-hilfe/my/offers',
    itHilfeRequest:           (id: string) => `/it-hilfe/${id}`,
    techniker:                '/techniker',
    technicianProfile:        (id: string) => `/techniker/${id}`,
    blog:                     '/blog',
    blogPost:                 (slug: string) => `/blog/${slug}`,
    blogSubmit:               '/blog/submit',
    workshops:                '/workshops',
    workshopsPropose:         '/workshops/propose',
    profil:                   '/profil',
    profilTechniker:          '/profil/techniker',
    login:                    '/auth/login',
    register:                 '/auth/register',
    forgotPassword:           '/auth/forgot-password',
    verifyEmail:              '/auth/verify-email',
    // Legal + membership pages — surface in the footer SSOT instead of
    // being hardcoded across components. Add new public pages here.
    impressum:                '/impressum',
    datenschutz:              '/datenschutz',
    agb:                      '/agb',
    transparenz:              '/transparenz',
    mitgliedWerden:           '/mitglied-werden',
  },
} as const
