export interface InstructionTemplate {
  id: string
  name: string
  description: string
  keywords?: string[]
  pagePatterns?: string[]
  framework?: string[]
  template: string
}

export function getDefaultTemplates(): InstructionTemplate[] {
  return [
    {
      id: 'general',
      name: 'General Content Change',
      description: 'Default template for general content modification requests',
      template: `# AI Agent Instructions: Content Modification Request

## 🎯 **Task Summary**
A user has suggested the following change to your website:

**Page:** {{page}}
**URL:** {{url}}
**User Suggestion:** "{{suggestion}}"
**Submitted by:** {{contact}}
**Timestamp:** {{timestamp}}

## 🔧 **Recommended Actions**

Based on the user's suggestion, consider implementing the following changes:

1. **Analyze the Target Page**
   - Review the content on {{page}}
   - Identify the specific section or element the user is referring to
   - Understand the current implementation

2. **Implement the Suggested Changes**
   - Modify the relevant content/layout/styling as requested
   - Ensure the changes align with the overall design system
   - Test the changes on different screen sizes

3. **Files to Consider**
   {{fileHints}}

## 🚀 **Framework-Specific Notes**
{{frameworkSpecificInstructions}}

## ✅ **Verification Checklist**
- [ ] Changes implemented as requested
- [ ] Design consistency maintained  
- [ ] Responsive design working properly
- [ ] Performance impact assessed
- [ ] Content accessibility reviewed

## 📝 **Additional Context**
- Site: {{siteName}}
- Framework: {{framework}}
- This suggestion was generated by AI-Native CMS

Please review the suggestion carefully and implement the changes as appropriate for your website's goals and design standards.`
    },
    
    {
      id: 'styling',
      name: 'Styling & Visual Changes',
      description: 'Template for styling, layout, and visual modification requests',
      keywords: ['color', 'font', 'size', 'bigger', 'smaller', 'style', 'design', 'layout', 'spacing', 'margin', 'padding', 'width', 'height'],
      template: `# AI Agent Instructions: Visual/Styling Changes

## 🎨 **Visual Modification Request**
**Page:** {{page}}
**User Request:** "{{suggestion}}"
**Submitted by:** {{contact}}

## 🔧 **Styling Implementation Steps**

1. **Identify Target Elements**
   - Locate the specific UI elements mentioned in: "{{suggestion}}"
   - Check current CSS/styling implementation
   - Review design system consistency

2. **Implement Visual Changes**
   - Modify CSS/styling as requested
   - Consider responsive design implications
   - Maintain accessibility standards (contrast, focus states)

3. **Framework-Specific Approach**
   {{frameworkSpecificInstructions}}

4. **Files to Modify**
   {{fileHints}}

## 🎯 **Common Styling Tasks**
Based on the request, you may need to:
- Adjust font sizes, colors, or typography
- Modify spacing (margins, padding)
- Change layout dimensions or positioning  
- Update component styling or themes
- Modify responsive breakpoints

## ✅ **Testing Checklist**
- [ ] Visual changes applied correctly
- [ ] Responsive design maintained
- [ ] Accessibility standards met
- [ ] Cross-browser compatibility checked
- [ ] Performance impact minimal

## 📱 **Device Testing**
Ensure changes work well on:
- Desktop (1920x1080, 1366x768)
- Tablet (768px width)  
- Mobile (375px width)

This styling request was processed by AI-Native CMS for {{siteName}}.`
    },

    {
      id: 'content',
      name: 'Content Updates',
      description: 'Template for text content, copy, and information changes',
      keywords: ['text', 'content', 'copy', 'information', 'add', 'remove', 'update', 'change', 'title', 'description', 'paragraph'],
      template: `# AI Agent Instructions: Content Update Request

## 📝 **Content Modification Task**
**Page:** {{page}}
**URL:** {{url}}
**Content Request:** "{{suggestion}}"
**Submitted by:** {{contact}}

## 📋 **Content Implementation Steps**

1. **Locate Content Section**
   - Find the specific content area mentioned in: "{{suggestion}}"
   - Review current text/copy
   - Understand content structure and hierarchy

2. **Update Content**
   - Modify text content as requested
   - Maintain consistent tone and brand voice
   - Ensure grammatical correctness
   - Check for SEO implications

3. **Content Management Approach**
   {{frameworkSpecificInstructions}}

4. **Files to Update**
   {{fileHints}}

## 📚 **Content Guidelines**
- Keep content clear and concise
- Maintain consistent brand voice
- Ensure accessibility (proper headings, alt text)
- Consider SEO keywords if applicable
- Check for typos and grammar

## 🔍 **SEO Considerations**
If the content change affects:
- Page titles (update meta title)
- Headings (maintain H1-H6 hierarchy)  
- Key descriptions (update meta description)
- Image content (update alt attributes)

## ✅ **Content Review Checklist**
- [ ] Content updated as requested
- [ ] Brand voice and tone maintained
- [ ] Grammar and spelling checked
- [ ] SEO impact assessed
- [ ] Accessibility standards met
- [ ] Content hierarchy preserved

## 🎯 **Content Types to Consider**
Based on the page {{page}}, this might involve:
- Headlines and titles
- Body copy and paragraphs
- Call-to-action buttons
- Image captions
- Navigation text
- Footer information

This content update was processed by AI-Native CMS for {{siteName}}.`
    },

    {
      id: 'navigation',
      name: 'Navigation & Menu Changes', 
      description: 'Template for navigation, menu, and link modifications',
      keywords: ['menu', 'navigation', 'nav', 'link', 'button', 'header', 'footer', 'sidebar'],
      pagePatterns: ['nav', 'menu', 'header', 'footer'],
      template: `# AI Agent Instructions: Navigation Modification

## 🧭 **Navigation Change Request**
**Page:** {{page}}
**Navigation Request:** "{{suggestion}}"
**Submitted by:** {{contact}}

## 🔗 **Navigation Implementation Steps**

1. **Identify Navigation Area**
   - Locate the specific navigation element: "{{suggestion}}"
   - Review current menu structure
   - Check navigation hierarchy and organization

2. **Implement Navigation Changes**
   - Modify menu items, links, or structure
   - Ensure consistent navigation patterns
   - Update routing/linking as needed
   - Test navigation flow

3. **Framework Navigation Patterns**
   {{frameworkSpecificInstructions}}

4. **Files to Modify**
   {{fileHints}}

## 🗺️ **Navigation Best Practices**
- Maintain clear navigation hierarchy
- Ensure mobile responsiveness
- Use descriptive link text
- Implement proper focus states
- Consider breadcrumb navigation if needed

## 📱 **Mobile Navigation**
If affecting mobile navigation:
- Test hamburger menu functionality
- Ensure touch targets are adequate (44px minimum)
- Verify swipe gestures work properly
- Check navigation accessibility on mobile

## ✅ **Navigation Testing Checklist**
- [ ] All navigation links work correctly
- [ ] Navigation hierarchy is logical
- [ ] Mobile navigation functions properly
- [ ] Keyboard navigation accessible
- [ ] Focus states visible and functional
- [ ] Active page states indicated

## 🎯 **Navigation Areas to Consider**
This change might affect:
- Primary navigation (header)
- Secondary navigation (sidebar)
- Footer navigation
- Breadcrumb navigation
- In-page navigation/anchors
- Call-to-action buttons

This navigation update was processed by AI-Native CMS for {{siteName}}.`
    },

    {
      id: 'feature',
      name: 'New Feature Request',
      description: 'Template for adding new functionality or features',
      keywords: ['add', 'new', 'feature', 'functionality', 'implement', 'create', 'build'],
      template: `# AI Agent Instructions: New Feature Implementation

## ⭐ **Feature Request**
**Page:** {{page}}
**Feature Request:** "{{suggestion}}"
**Submitted by:** {{contact}}
**Complexity:** This appears to be a feature addition request

## 🔧 **Feature Development Steps**

1. **Analyze Feature Requirements**
   - Break down the request: "{{suggestion}}"
   - Identify technical requirements
   - Consider existing system integration
   - Estimate implementation scope

2. **Plan Implementation**
   - Design feature architecture
   - Identify required components/modules
   - Consider data storage needs
   - Plan user interface elements

3. **Framework-Specific Implementation**
   {{frameworkSpecificInstructions}}

4. **Development Files**
   {{fileHints}}

## ⚠️ **Implementation Considerations**

**Before implementing this feature, consider:**
- **Scope:** Is this a simple addition or complex feature?
- **Dependencies:** What existing code/libraries are needed?
- **Data:** Does this require database changes?
- **UI/UX:** How should this integrate with existing design?
- **Performance:** Will this impact site performance?
- **Testing:** How will this feature be tested?

## 🚀 **Suggested Implementation Approach**

1. **Start Small:** Implement a basic version first
2. **Test Early:** Verify functionality before adding complexity  
3. **User Experience:** Ensure intuitive user interaction
4. **Documentation:** Document any new functionality
5. **Error Handling:** Include proper error states

## ✅ **Feature Implementation Checklist**
- [ ] Requirements clearly understood
- [ ] Feature architecture planned
- [ ] UI/UX design considered
- [ ] Code implementation completed
- [ ] Feature tested thoroughly
- [ ] Error handling implemented
- [ ] Documentation updated
- [ ] Performance impact assessed

## 💡 **Development Tips**
- Break complex features into smaller components
- Reuse existing design patterns and components
- Consider progressive enhancement
- Implement proper loading and error states
- Test across different devices and browsers

**Note:** This appears to be a significant feature request. Consider if this aligns with your site's goals and development priorities.

This feature request was processed by AI-Native CMS for {{siteName}}.`
    }
  ]
}

// Helper function to find best template for a suggestion
export function findBestTemplate(suggestion: string, page: string, templates: InstructionTemplate[]): InstructionTemplate {
  const suggestionLower = suggestion.toLowerCase()
  const pageLower = page.toLowerCase()

  // First, try keyword matching
  for (const template of templates) {
    if (template.keywords) {
      for (const keyword of template.keywords) {
        if (suggestionLower.includes(keyword.toLowerCase())) {
          return template
        }
      }
    }
  }

  // Then try page pattern matching
  for (const template of templates) {
    if (template.pagePatterns) {
      for (const pattern of template.pagePatterns) {
        if (pageLower.includes(pattern) || page.includes(pattern)) {
          return template
        }
      }
    }
  }

  // Return general template as fallback
  return templates.find(t => t.id === 'general') || templates[0]
}